/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
/* tslint:disable */
/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */ export var styles = ['.search-result[_ngcontent-%COMP%]{\n  border-bottom: 1px solid gray;\n  border-left: 1px solid gray;\n  border-right: 1px solid gray;\n  width:195px;\n  height: 16px;\n  padding: 5px;\n  background-color: white;\n  cursor: pointer;\n}\n\n.search-result[_ngcontent-%COMP%]:hover {\n  color: #eee;\n  background-color: #607D8B;\n}\n\n#search-box[_ngcontent-%COMP%]{\n  width: 200px;\n  height: 20px;\n}'];
//# sourceMappingURL=hero-search.component.css.shim.ngstyle.js.map